name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - drewhoener
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: mod-version
    attributes:
      label: Game Version
      description: What version of UIInfoSuite2 are you running?
      options:
        - v2.3.0-alpha-2
        - v2.3.0-alpha-1
        - v2.2.10 (Stardew 1.5)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: multiplayer
    attributes:
      label: Multiplayer
      description: |
        Did this issue occur in multiplayer?  
        If so, indicate whether you were the client or the host.
      options:
        - Single Player
        - Multiplayer (Host)
        - Multiplayer (Non-Host)
        - Split-Screen
      default: 0
    validations:
      required: true
  - type: dropdown
    id: breaking
    attributes:
      label: Breaking Bug
      description: |
        Is this a Breaking Issue?
        Does the game crash, or does the mod refuse to load?
      options:
        - Non-Breaking
        - Breaking (Game crashes)
        - Breaking (Mod doesn't load)
      default: 0
    validations:
      required: true
  - type: input
    id: log-link
    attributes:
      label: SMAPI Log
      description: |
        Is this a breaking bug? Are there UIInfoSuite2 errors in your log?
        If so, please upload it to https://smapi.io/log and share the link below
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please describe what happened, as well as what you expected to happen.
        If possible, please include images or steps to reproduce your issue!
      placeholder: Tell us what you see!
    validations:
      required: true